name: CI-PR

on: [pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: npm ci
    - run: npm run build

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: npm ci
    - name: test
      env:
        CI: true
        COVERAGE: true
        FLAKEY: false
      run: npm run test
    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@v1.0.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
